#define CMD_FORWARD 0x1C
#define CMD_LEFT 0x1F
#define CMD_RIGHT 0x1E
#define CMD_BACKWARD 0x1D

#define CMD_OPEN_CLAW 0x1B 
#define CMD_CLOSE_SERVO 0x1A 
#define CMD_BATTERY 0xE1
#define CMD_READCOLOR 0xE0
#define CMD_STOP 0x19
#define CMD_POSE 0x00
#define CMD_RESET 0x17
#define CMD_RETURN 0x16

#define CMD_COLOR_VALUE 0x18
#define CMD_COLOR_MASK 0x1F
#define MASK_RED 0x80
#define MASK_GREEN 0x40
#define MASK_BLUE 0x20